# Puerto solicitado en la guía
server.port=8081

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/workshop_jpa
# Si tus credenciales locales no son 'postgres', cámbialas aquí:
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA e Hibernate - Sincronización
# Usamos 'update' para que Spring cree las tablas por nosotros al arrancar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect